services:
    # Custom validators
    rk_helper_module.validator.list_entry.validator:
        class: RK\HelperModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@rk_helper_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: rk_helper_module.validator.list_entry.validator }
