<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\HelperModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\HelperModule\Entity\LinkerEntity;

/**
 * Event base class for filtering linker processing.
 */
class AbstractFilterLinkerEvent extends Event
{
    /**
     * @var LinkerEntity Reference to treated entity instance.
     */
    protected $linker;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterLinkerEvent constructor.
     *
     * @param LinkerEntity $linker Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(LinkerEntity $linker, $entityChangeSet = [])
    {
        $this->linker = $linker;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return LinkerEntity
     */
    public function getLinker()
    {
        return $this->linker;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
