<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\HelperModule\Block\Form\Type;

use RK\HelperModule\Block\Form\Type\Base\AbstractItemBlockType;

/**
 * Detail block form type implementation class.
 */
class ItemBlockType extends AbstractItemBlockType
{
    // feel free to extend the detail block form type class here
}
