<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\HelperModule\Container\Base;

use Symfony\Component\Routing\RouterInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\LinkContainer\LinkContainerInterface;
use Zikula\PermissionsModule\Api\ApiInterface\PermissionApiInterface;
use RK\HelperModule\Helper\ControllerHelper;

/**
 * This is the link container service implementation class.
 */
abstract class AbstractLinkContainer implements LinkContainerInterface
{
    use TranslatorTrait;

    /**
     * @var RouterInterface
     */
    protected $router;

    /**
     * @var PermissionApiInterface
     */
    protected $permissionApi;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * LinkContainer constructor.
     *
     * @param TranslatorInterface    $translator       Translator service instance
     * @param Routerinterface        $router           Router service instance
     * @param PermissionApiInterface $permissionApi    PermissionApi service instance
     * @param ControllerHelper       $controllerHelper ControllerHelper service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        RouterInterface $router,
        PermissionApiInterface $permissionApi,
        ControllerHelper $controllerHelper
    ) {
        $this->setTranslator($translator);
        $this->router = $router;
        $this->permissionApi = $permissionApi;
        $this->controllerHelper = $controllerHelper;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * Returns available header links.
     *
     * @param string $type The type to collect links for
     *
     * @return array Array of header links
     */
    public function getLinks($type = LinkContainerInterface::TYPE_ADMIN)
    {
        $contextArgs = ['api' => 'linkContainer', 'action' => 'getLinks'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $contextArgs);

        $permLevel = LinkContainerInterface::TYPE_ADMIN == $type ? ACCESS_ADMIN : ACCESS_READ;

        // Create an array of links to return
        $links = [];

        if (LinkContainerInterface::TYPE_ACCOUNT == $type) {

            return $links;
        }

        $routeArea = LinkContainerInterface::TYPE_ADMIN == $type ? 'admin' : '';
        if (LinkContainerInterface::TYPE_ADMIN == $type) {
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_READ)) {
                $links[] = [
                    'url' => $this->router->generate('rkhelpermodule_linker_index'),
                    'text' => $this->__('Frontend', 'rkhelpermodule'),
                    'title' => $this->__('Switch to user area.', 'rkhelpermodule'),
                    'icon' => 'home'
                ];
            }
        } else {
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('rkhelpermodule_linker_adminindex'),
                    'text' => $this->__('Backend', 'rkhelpermodule'),
                    'title' => $this->__('Switch to administration area.', 'rkhelpermodule'),
                    'icon' => 'wrench'
                ];
            }
        }
        
        if (in_array('linker', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Linker:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('rkhelpermodule_linker_' . $routeArea . 'view'),
                'text' => $this->__('Linkers', 'rkhelpermodule'),
                'title' => $this->__('Linkers list', 'rkhelpermodule')
            ];
        }
        if (in_array('carouselItem', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':CarouselItem:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('rkhelpermodule_carouselitem_' . $routeArea . 'view'),
                'text' => $this->__('Carousel items', 'rkhelpermodule'),
                'title' => $this->__('Carousel items list', 'rkhelpermodule')
            ];
        }
        if (in_array('carousel', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Carousel:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('rkhelpermodule_carousel_' . $routeArea . 'view'),
                'text' => $this->__('Carousells', 'rkhelpermodule'),
                'title' => $this->__('Carousells list', 'rkhelpermodule')
            ];
        }
        if (in_array('image', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Image:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('rkhelpermodule_image_' . $routeArea . 'view'),
                'text' => $this->__('Images', 'rkhelpermodule'),
                'title' => $this->__('Images list', 'rkhelpermodule')
            ];
        }
        if (in_array('info', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Info:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('rkhelpermodule_info_' . $routeArea . 'view'),
                'text' => $this->__('Infos', 'rkhelpermodule'),
                'title' => $this->__('Infos list', 'rkhelpermodule')
            ];
        }
        if ($routeArea == 'admin' && $this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
            $links[] = [
                'url' => $this->router->generate('rkhelpermodule_config_config'),
                'text' => $this->__('Configuration', 'rkhelpermodule'),
                'title' => $this->__('Manage settings for this application', 'rkhelpermodule'),
                'icon' => 'wrench'
            ];
        }

        return $links;
    }

    /**
     * Returns the name of the providing bundle.
     *
     * @return string The bundle name
     */
    public function getBundleName()
    {
        return 'RKHelperModule';
    }
}
