<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\HelperModule\Entity;

use RK\HelperModule\Entity\Base\AbstractLinkerEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for linker entities.
 * @ORM\Entity(repositoryClass="RK\HelperModule\Entity\Repository\LinkerRepository")
 * @ORM\Table(name="rk_helper_linker",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class LinkerEntity extends BaseEntity
{
    // feel free to add your own methods here
}
