<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\HelperModule\Listener;

use RK\HelperModule\Listener\Base\AbstractUsersListener;

/**
 * Event handler implementation class for events of the Users module.
 */
class UsersListener extends AbstractUsersListener
{
    // feel free to enhance the parent methods
}
